services:
  Inverter_EV-charger:
    image: openplc-docker
    container_name: Inverter_EV-charger
    ports:
      - "8010:8080"
      - "510:502"
    command: >
      bash -c "/home/openplc/scripts/run.sh"
    volumes:
      - /home/kali/Desktop/GamifiedICS/init/OpenPLC/EV-charger/Inverter/openplc:/home/openplc
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.10

  Communications_EV-charger:
    image: openplc-docker
    container_name: Communications_EV-charger
    user: root
    ports:
      - "8011:8080"
      - "511:502"
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    command: >
      bash -c "apt update &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               /home/openplc/scripts/run.sh"
    volumes:
      - /home/kali/Desktop/GamifiedICS/init/OpenPLC/EV-charger/Communications/openplc:/home/openplc
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.11
        
        
 
  
  





#  placeholderPLC_Monorail:
#    image: openplc-docker
#    container_name: placeholderPLC_Monorail
#    user: root
#    ports:
#      - "8020:8080"
#      - "520:502"
#    cap_add:
#      - NET_ADMIN
#    security_opt:
#      - apparmor:unconfined
#    command: >
#      bash -c "apt update &&
#               apt install -y net-tools &&
#               apt install -y iputils-ping &&
#               apt install -y iptables &&
#               apt install -y nmap &&
#               /home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Monorail:
#        ipv4_address: 192.168.101.10










  sql-server_Power-plant:
    image: mysql
    container_name: sql-server_Power-plant
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_Power-plant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - sql-server_data_Power-plant:/var/lib/mysql
      - ./init/db_Power-plant.sql:/docker-entrypoint-initdb.d/db_Power-plant.sql:ro
    networks:
      network_Power-plant:
        ipv4_address: 192.168.102.3

  wordpress_Power-plant:
    image: wordpress:latest
    container_name: wordpress_Power-plant
    user: root
    ports:
      - "8002:80"
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      WORDPRESS_DB_HOST: sql-server_Power-plant
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_Power-plant
    command: >
      bash -c "apt update &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               iptables -P INPUT DROP &&
               iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT &&
               iptables -A INPUT -i lo -j ACCEPT &&
               iptables -A INPUT -p tcp --dport 80 -j ACCEPT &&
               apache2-foreground"
    volumes:
      #- wordpress_data_Power-plant:/var/www/html
      - /home/kali/Desktop/GamifiedICS/wordpressData/wordpress-data_Power-plant/html:/var/www/html
    depends_on:
      - sql-server_Power-plant
    networks:
      network_Power-plant:
        ipv4_address: 192.168.102.2

#  Cooling-pump_Power-plant:
#    image: openplc-docker
#    container_name: Cooling-pump_Power-plant
#    ports:
#      - "8030:8080"
#      - "530:502"
#    command: >
#      bash -c "/home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Power-plant:
#        ipv4_address: 192.168.102.10

#  Geiger-counter_Power-plant:
#    image: openplc-docker
#    container_name: Geiger-counter_Power-plant
#    ports:
#      - "8031:8080"
#      - "531:502"
#    command: >
#      bash -c "/home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Power-plant:
#        ipv4_address: 192.168.102.11

#  Heat-sensor_Power-plant:
#    image: openplc-docker
#    container_name: Heat-sensor_Power-plant
#    ports:
#      - "8032:8080"
#      - "532:502"
#    command: >
#      bash -c "/home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Power-plant:
#        ipv4_address: 192.168.102.12

#  Inverter_Power-plant:
#    image: openplc-docker
#    container_name: Inverter_Power-plant
#    ports:
#      - "8033:8080"
#      - "533:502"
#    command: >
#      bash -c "/home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Power-plant:
#        ipv4_address: 192.168.102.13

#  Steam-turbine-CS_Power-plant:
#    image: openplc-docker
#    container_name: Steam-turbine-CS_Power-plant
#    ports:
#      - "8034:8080"
#      - "534:502"
#    command: >
#      bash -c "/home/openplc/run.sh"
#    volumes:
#      - /home/kali/Desktop/GamifiedICS/OpenPLC-Setup:/home/openplc/scripts
#    networks:
#      network_Power-plant:
#        ipv4_address: 192.168.102.14










  guacd_Laptop:
    image: guacamole/guacd
    container_name: guacd_Laptop

  guac_mysql_Laptop:
    image: mysql
    container_name: guac_mysql_Laptop
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guac_db_Laptop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - guac_mysql_data_Laptop:/var/lib/mysql
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  guacamole_Laptop:
    image: guacamole/guacamole
    container_name: guacamole_Laptop
    depends_on:
      - guacd_Laptop
      - guac_mysql_Laptop
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOSTNAME: guac_mysql_Laptop
      MYSQL_DATABASE: guac_db_Laptop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      GUACD_HOSTNAME: guacd_Laptop
      GUACD_PORT: 4822

  Laptop:
    image: rastasheep/ubuntu-sshd
    container_name: Laptop
    command: >
      bash -c "id -u user &>dev/null || useradd -s /bin/bash user &&
               echo "user:password" | chpasswd &&
               chmod 755 /home/user &&
               usermod -aG sudo user &&
               apt update &&
               apt install sudo &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               /home/user/install_mbpoll.sh &&
               /usr/sbin/sshd -D"
    volumes:
      - Laptop_data:/home/user
      - /home/kali/Desktop/GamifiedICS/scripts/install_mbpoll.sh:/home/user/install_mbpoll.sh
    depends_on:
      - guacd_Laptop
      - guac_mysql_Laptop
      - guacamole_Laptop










  guacd_EV-charger:
    image: guacamole/guacd
    container_name: guacd_EV-charger
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.50

  guac_mysql_EV-charger:
    image: mysql
    container_name: guac_mysql_EV-charger
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guac_db_EV-charger
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - guac_mysql_data_EV-charger:/var/lib/mysql
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.51

  guacamole_EV-charger:
    image: guacamole/guacamole
    container_name: guacamole_EV-charger
    depends_on:
      - guacd_EV-charger
      - guac_mysql_EV-charger
    ports:
      - "8090:8080"
    environment:
      MYSQL_HOSTNAME: guac_mysql_EV-charger
      MYSQL_DATABASE: guac_db_EV-charger
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      GUACD_HOSTNAME: guacd_EV-charger
      GUACD_PORT: 4822
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.52

  EV-charger:
    image: rastasheep/ubuntu-sshd
    container_name: EV-charger
    command: >
      bash -c "id -u user &>dev/null || useradd -s /bin/bash user &&
               echo "user:password" | chpasswd &&
               chmod 755 /home/user &&
               usermod -aG sudo user &&
               apt update &&
               apt install sudo &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               /home/user/install_mbpoll.sh &&
               /usr/sbin/sshd -D"
    volumes:
      - EV-charger_data:/home/user
      - /home/kali/Desktop/GamifiedICS/scripts/install_mbpoll.sh:/home/user/install_mbpoll.sh
    depends_on:
      - guacd_EV-charger
      - guac_mysql_EV-charger
      - guacamole_EV-charger
    networks:
      network_EV-charger:
        ipv4_address: 192.168.100.53










  guacd_Monorail:
    image: guacamole/guacd
    container_name: guacd_Monorail

  guac_mysql_Monorail:
    image: mysql
    container_name: guac_mysql_Monorail
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guac_db_Monorail
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - guac_mysql_data_Monorail:/var/lib/mysql
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  guacamole_Monorail:
    image: guacamole/guacamole
    container_name: guacamole_Monorail
    depends_on:
      - guacd_Monorail
      - guac_mysql_Monorail
    ports:
      - "8091:8080"
    environment:
      MYSQL_HOSTNAME: guac_mysql_Monorail
      MYSQL_DATABASE: guac_db_Monorail
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      GUACD_HOSTNAME: guacd_Monorail
      GUACD_PORT: 4822

  Monorail:
    image: rastasheep/ubuntu-sshd
    container_name: Monorail
    command: >
      bash -c "id -u user &>dev/null || useradd -s /bin/bash user &&
               echo "user:password" | chpasswd &&
               chmod 755 /home/user &&
               usermod -aG sudo user &&
               apt update &&
               apt install sudo &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               /home/user/install_mbpoll.sh &&
               /usr/sbin/sshd -D"
    volumes:
      - Monorail_data:/home/user
      - /home/kali/Desktop/GamifiedICS/scripts/install_mbpoll.sh:/home/user/install_mbpoll.sh
    depends_on:
      - guacd_Monorail
      - guac_mysql_Monorail
      - guacamole_Monorail










  guacd_Power-plant:
    image: guacamole/guacd
    container_name: guacd_Power-plant

  guac_mysql_Power-plant:
    image: mysql
    container_name: guac_mysql_Power-plant
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guac_db_Power-plant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - guac_mysql_data_Power-plant:/var/lib/mysql
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  guacamole_Power-plant:
    image: guacamole/guacamole
    container_name: guacamole_Power-plant
    depends_on:
      - guacd_Power-plant
      - guac_mysql_Power-plant
    ports:
      - "8092:8080"
    environment:
      MYSQL_HOSTNAME: guac_mysql_Power-plant
      MYSQL_DATABASE: guac_db_Power-plant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      GUACD_HOSTNAME: guacd_Power-plant
      GUACD_PORT: 4822

  Power-plant:
    image: rastasheep/ubuntu-sshd
    container_name: Power-plant
    command: >
      bash -c "id -u user &>dev/null || useradd -s /bin/bash user &&
               echo "user:password" | chpasswd &&
               chmod 755 /home/user &&
               usermod -aG sudo user &&
               apt update &&
               apt install sudo &&
               apt install -y net-tools &&
               apt install -y iputils-ping &&
               apt install -y iptables &&
               apt install -y nmap &&
               /home/user/install_mbpoll.sh &&
               /usr/sbin/sshd -D"
    volumes:
      - Power-plant_data:/home/user
      - /home/kali/Desktop/GamifiedICS/scripts/install_mbpoll.sh:/home/user/install_mbpoll.sh
    depends_on:
      - guacd_Power-plant
      - guac_mysql_Power-plant
      - guacamole_Power-plant
      
      
      
      
      
      
      
      
      
      
      
volumes:
  sql-server_data_Power-plant:
  #wordpress_data_Power-plant:
  guac_mysql_data_Laptop:
  guac_mysql_data_EV-charger:
  guac_mysql_data_Monorail:
  guac_mysql_data_Power-plant:
  Laptop_data:
  EV-charger_data:
  Monorail_data:
  Power-plant_data:

networks:
  network_EV-charger:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  network_Monorail:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  network_Power-plant:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24
