;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Mission.HackEV",NewTagName="Mission.Mission01")
+GameplayTagRedirects=(OldTagName="Mission.Primary.HackEV.AcquireLaptop.Acquired",NewTagName="Mission.Primary.HackEV.AcquireLaptop.GotLaptop")
+GameplayTagRedirects=(OldTagName="Mission.Primary.PrepareYourself.MotelDoor",NewTagName="Mission.Primary.PrepareYourself.SuccessTrigger")
+GameplayTagRedirects=(OldTagName="Mission.Primary.HackEV.Trigger",NewTagName="Mission.Primary.HackEV.SuccessTrigger")
+GameplayTagRedirects=(OldTagName="Mission.Primary.HackEV.ReachedRefuelStation",NewTagName="Mission.Primary.HackEV.ReachRefuelStation")
+GameplayTagRedirects=(OldTagName="Mission.Primary.HackEV.HideSpot",NewTagName="Mission.Primary.HackEV.InHideSpot")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Mission",DevComment="\'\'")
+GameplayTagList=(Tag="Mission.Event.Fail",DevComment="")
+GameplayTagList=(Tag="Mission.Event.IntroCine",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Mission01Start",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Level01",DevComment="")
+GameplayTagList=(Tag="Mission.Mission01",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems",DevComment="Example Mission Optional Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Item",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.ItemsPlaced",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone",DevComment="Example Mission Primary Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.ConeTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.DoorUnlocked",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.GoneToDoor",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Keycard",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.KeycardCollected",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Cone",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.AcquireBluetoothUSB.GotUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.AcquireMonoKeycard.GotMonoKeycard",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Cyber",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.CyberArrived",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.CyberDestroyed",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.CyberTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.HideSpotTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.HVTArrived",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.HVTReturned",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.HVTReturnTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.HVTTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.InHideSpot",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.InsertUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.Cybertruck",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.EVCharger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.HideSpot",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.HVT",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.MonoKeycard",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.Refuel Station",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker.ReturnHideSpot",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.MotelDoor",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.ReachRefuelStation",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.RefuelStationTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.ReturnHideSpotTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.SuccessTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.AcquireBluetoothUSB.GotUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.AcquireLaptop.GotLaptop",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.BluetoothUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.Laptop",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.MotelExit",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.SuccessTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Prologue",DevComment="")

