;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Mission.Event.Fail",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Level01",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems",DevComment="Example Mission Optional Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Item",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.ItemsPlaced",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone",DevComment="Example Mission Primary Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.ConeTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.DoorUnlocked",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.GoneToDoor",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Keycard",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.KeycardCollected",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Cone",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Success",DevComment="")

