;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Mission.HackEV",NewTagName="Mission.Mission01")
+GameplayTagRedirects=(OldTagName="Mission.Primary.HackEV.AcquireLaptop.Acquired",NewTagName="Mission.Primary.HackEV.AcquireLaptop.GotLaptop")
+GameplayTagRedirects=(OldTagName="Mission.Primary.PrepareYourself.MotelDoor",NewTagName="Mission.Primary.PrepareYourself.SuccessTrigger")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Mission",DevComment="\'\'")
+GameplayTagList=(Tag="Mission.Event.Fail",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Level01",DevComment="")
+GameplayTagList=(Tag="Mission.Mission01",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems",DevComment="Example Mission Optional Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Item",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.ItemsPlaced",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.Basket",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Optional.PickUpItems.Start",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone",DevComment="Example Mission Primary Objective (Provided by Plugin)")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.ConeTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.DoorUnlocked",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.GoneToDoor",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Keycard",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.KeycardCollected",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Cone",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.Door",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Marker.SearchArea",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.GoToCone.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Marker",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.HackEV.Trigger",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.AcquireBluetoothUSB.GotUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.AcquireLaptop.GotLaptop",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.BluetoothUSB",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.Laptop",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Marker.MotelExit",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.Success",DevComment="")
+GameplayTagList=(Tag="Mission.Primary.PrepareYourself.SuccessTrigger",DevComment="")
+GameplayTagList=(Tag="Mission.Prologue",DevComment="")

